meta_product_name: "The Book Collective"
meta_title: "The Book Collective - Discover, Borrow, JOIN"
meta_description: "Find your favorite books through your neighbor's library"
meta_image: "rotate3.jpg"
twitter_account: "@will30303_twitter_account"
